; Script generated by Inno Setup Script Wizard

#define MyAppName "Face_Detection1"
#define MyAppVersion "1.5"
#define MyAppPublisher "My Company, Inc."
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "face_detection1.exe"

[Setup]
AppId={{772CAF61-C92A-4A02-86C6-3592371393D5}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}

ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

DisableProgramGroupPage=yes
OutputDir=C:\Users\Kusha\AndroidStudioProjects\demo2flutter\installers
OutputBaseFilename=FaceDetection1

SetupIconFile=C:\Users\Kusha\Downloads\face_scan_icon_149480.ico

Compression=lzma
SolidCompression=yes
WizardStyle=modern

; Uncomment for non-admin install
;PrivilegesRequired=lowest

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create Desktop Icon"; Flags: unchecked

[Files]
; -------------------------------
; MAIN APP FILES
; -------------------------------
Source: "C:\Users\Kusha\AndroidStudioProjects\demo2flutter\build\windows\x64\runner\Release\face_detection1.exe"; DestDir: "{app}"; Flags: ignoreversion

Source: "C:\Users\Kusha\AndroidStudioProjects\demo2flutter\build\windows\x64\runner\Release\camera_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kusha\AndroidStudioProjects\demo2flutter\build\windows\x64\runner\Release\dartcv.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kusha\AndroidStudioProjects\demo2flutter\build\windows\x64\runner\Release\face_detection_tflite_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kusha\AndroidStudioProjects\demo2flutter\build\windows\x64\runner\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kusha\AndroidStudioProjects\demo2flutter\build\windows\x64\runner\Release\libtensorflowlite_c-win.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kusha\AndroidStudioProjects\demo2flutter\build\windows\x64\runner\Release\tflite_custom_ops.dll"; DestDir: "{app}"; Flags: ignoreversion

Source: "C:\Users\Kusha\AndroidStudioProjects\demo2flutter\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs

; -------------------------------
; VC++ REDISTRIBUTABLE (IMPORTANT)
; -------------------------------
Source: "C:\Users\Kusha\AndroidStudioProjects\demo2flutter\installers\VC_redist.x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Install VC++ ONLY if not already installed
Filename: "{tmp}\VC_redist.x64.exe"; \
    Parameters: "/install /quiet /norestart"; \
    StatusMsg: "Installing Visual C++ Redistributable..."; \
    Flags: waituntilterminated; \
    Check: not IsVCRedistInstalled

; Launch app after install
Filename: "{app}\{#MyAppExeName}"; \
    Description: "Launch {#MyAppName}"; \
    Flags: nowait postinstall skipifsilent

[Code]
function IsVCRedistInstalled(): Boolean;
var
  Installed: Cardinal;
begin
  Result :=
    RegQueryDWordValue(
      HKLM,
      'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64',
      'Installed',
      Installed
    ) and (Installed = 1);
end;